### PR TITLE
Lectures @ home update for lecture on 4th February 2021

### PR DESCRIPTION
**Pull request by MalteRei**

### CODE REVIEW

**Review by spethso — CHANGES_REQUESTED** [review]
Removed deprecated Lectures@Home file and updated event description for grammar and style.

I would request speaker names and pictures in the event's page.

**Comment by MalteRei** [comment]
@dom

> Removed deprecated Lectures@Home file and updated event description for grammar and style.
> 
> I would request speaker names and pictures in the event's page.


I migrated the speaker images over from the old website.
While I understand the want to have such information, I am not sure if it is a great idea to start adding stuff that are not in the design. This might cause each page to look different.
@Dominik-MCC do you want to contribute your opinion?

image

**Comment by spethso** [comment]
> I migrated the speaker images over from the old website.
> While I understand the want to have such information, I am not sure if it is a great idea to start adding stuff that are not in the design. This might cause each page to look different.
> @Dominik-MCC do you want to contribute your opinion?
> 
> image

Actually, I like the looks a lot. I do not think this is disturbing at all

**Review by MalteRei — COMMENTED** [review]
Grammar 🙆‍♂️

**Comment by MalteRei** [comment]
Now I am confused by GitHub. @spethso you requested changes and provided the commits for them. It is still showing changes requested. When I click on your requested changes I can only comment and not approve because a pull request creator can not approve the own pull request. Who else is supposed to approve your requested changes then?

**Review by spethso — APPROVED** [review]

**Comment by spethso** [comment]
> Now I am confused by GitHub. @spethso you requested changes and provided the commits for them. It is still showing changes requested. When I click on your requested changes I can only comment and not approve because a pull request creator can not approve the own pull request. Who else is supposed to approve your requested changes then?

It seems I could approve it :)

**Pull request merged**
